### ISSUE TITLE
Could not write tweaks to shader fiels?

### ISSUE THREAD

**Issue by 74Flyer** [LB767/OpenShade#1]
Recently tied to add two presets from REX onto p3dv4 and upon applying it gave me that error that it didnt apply, is there anything i can do?

**Comment by LB767** [comment]
I just tested all the REX presets and they work fine on my side. 
Do you only have this issue with these 2 presets? If so could you link them here so I can have a look.

**Comment by 74Flyer** [comment]
I fixed it. colorfullness wasnt turned on :)

**Comment by LB767** [comment]
Erm ok. It should work just fine with Colorfullness off though so I'm not sure what happened there?

I'll close the issue but feel free to give me more details about the problem if it happens again.
In any case thanks for taking the time to report this.
